openapi: 3.0.1
info:
  title: Simple Voting Service
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/vote:
    post:
      tags:
        - vote-api
      requestBody:
        description: vote to add to the Urn
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VoteType"
      operationId: codeapp.application.add_vote
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: string
  /api/results/{useless}:
    get:
      tags:
        - results-api
      summary: Get the voting results
      operationId: codeapp.application.get_urn
      parameters:
        - name: useless
          in: path
          required: true
          schema:
            type: string
            example: 'useless'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    VoteType:
      type: object
      required:
        - candidate
      properties:
        voter:
          type: string
          example: Matteo
        candidate:
          type: string
          example: Matt Ca
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
